---
extends:
  - eslint:recommended
  - plugin:node/recommended
  - plugin:import/recommended
  - prettier
plugins:
  - node
  - prettier
  - standard
  - import
  - promise
rules:
  node/no-deprecated-api: off
  prettier/prettier: error
  block-scoped-var: error
  eqeqeq: error
  no-warning-comments: warn
  no-var: error
  prefer-const: off
  node/no-unsupported-features/es-syntax:
    - error
    - ignores: ['modules']
env:
  node: true
  es2021: true
parserOptions:
  ecmaVersion: 12
  allowImportExportEverywhere: true
